[target.x86_64-pc-windows-msvc]
linker = "rust-lld.exe"
rustdocflags = [
    "-Clinker=rust-lld.exe"
]
rustflags = [
    # "-C",
    # "link-arg=/STACK:8000000",
    "-Zshare-generics=n",
    "-Zthreads=0"
]
